// Mapea prefijos de ruta → page_key de role_permissions. DEBE mantenerse en
// sincronía con las pageKey del sidebar: el sidebar muestra/oculta con la clave
// granular y el middleware DEBE exigir la MISMA clave (si no, hay bloqueos
// falsos o fugas de acceso por URL). Ordenado del más específico al más
// genérico: pageKeyForPath devuelve la primera coincidencia.
export const ROUTE_TO_PAGE_KEY: [string, string][] = [
  ['/academic/convocatorias-matriculas', 'academic_convocatorias_report'],
  ['/academic/moodle-access', 'moodle_access'],
  ['/finance/cashpay', 'finance_cashpay'],
  ['/academic/estudiantes-convocatoria', 'academic_convocatoria_students'],
  ['/planning/effectiveness/dashboard', 'effectiveness_dashboard'],
  ['/hr/capacitaciones/participantes', 'hr_capacitacion_participantes'],
  ['/planning/assessment/dashboard', 'assessment_dashboard'],
  ['/academic/teaching-assignments', 'academic_teaching'],
  ['/planning/assessment/measures', 'assessment_measures'],
  ['/planning/effectiveness/kpis', 'effectiveness_kpis'],
  ['/planning/effectiveness/plan', 'effectiveness_plan'],
  ['/reports/estado-estudiantes', 'report_student_status'],
  ['/academic/transfer-credits', 'academic_transfer_credits'],
  ['/academic/transfer-schemes', 'academic_transfer_schemes'],
  ['/academic/acta-asignatura', 'academic_acta_course'],
  ['/admision/nueva-matricula', 'admision_nueva_matricula'],
  ['/finance/books-operations', 'finance_books_operations'],
  ['/registrar/document-types', 'registrar_document_types'],
  ['/registrar/isic-cards', 'registrar_isic_cards'],
  ['/registrar/tramites', 'registrar_tramites'],
  ['/collection/scholarships', 'collection_scholarships'],
  ['/reports/estado-docentes', 'report_faculty_status'],
  ['/academic/billing-plans', 'academic_billing_plans'],
  ['/academic/convocatorias', 'academic_convocatorias'],
  ['/academic/grades-import', 'academic_grades_import'],
  ['/admissions/commissions', 'admissions_commissions'],
  ['/finance/otros-ingresos', 'finance_other_income'],
  ['/finance/reconciliation', 'finance_reconciliation'],
  ['/reports/accesos-portal', 'report_portal_logins'],
  ['/reports/auditor-campus', 'report_campus_audit'],
  ['/reports/moodle-status', 'report_moodle_status'],
  ['/academic/acta-detalle', 'academic_acta_detail'],
  ['/academic/grade-scales', 'academic_grade_scales'],
  ['/academic/moodle-actas', 'academic_moodle_actas'],
  ['/academic/classroom-links', 'academic_classroom_links'],
  ['/reports/tuition-audit', 'report_tuition_audit'],
  ['/academic/credentials', 'academic_credentials'],
  ['/academic/seguimiento', 'academic_tracking'],
  ['/academic/validations', 'academic_validations'],
  ['/admissions/documents', 'admissions_documents'],
  ['/finance/credit-rates', 'finance_credit_rates'],
  ['/academic/carruseles', 'academic_carousels'],
  ['/academic/curricular', 'academic_curricular'],
  ['/admision/matriculas', 'admision_matriculas'],
  ['/contracts/templates', 'contracts_templates'],
  ['/finance/debt-report', 'finance_debt_report'],
  ['/finance/recaudacion', 'finance_recaudacion'],
  ['/ia/sofia-supervisor', 'sofia_supervisor'],
  ['/planning/indicators', 'planning_indicators'],
  ['/planning/audit', 'planning_audit'],
  ['/planning/assessment', 'assessment_plan'],
  ['/academic/retencion', 'academic_retention'],
  ['/academic/schedules', 'academic_schedules'],
  ['/collection/bonuses', 'collection_bonuses'],
  ['/planning/dashboard', 'planning_dashboard'],
  ['/registrar/formatos', 'registrar_formatos'],
  ['/registrar/requests', 'registrar_requests'],
  ['/academic/concepts', 'academic_concepts'],
  ['/academic/examenes', 'academic_exams'],
  ['/academic/programs', 'academic_programs'],
  ['/academic/students', 'academic_student_profile'],
  ['/academic/syllabi', 'academic_syllabi'],
  ['/finance/conciliar', 'finance_conciliar'],
  ['/hr/capacitaciones', 'hr_capacitaciones'],
  ['/planning/progress', 'planning_progress'],
  ['/registrar/degrees', 'registrar_degrees'],
  ['/reports/egresados', 'report_graduates'],
  ['/ventas/prospectos', 'sales_prospectos'],
  ['/academic/account', 'academic_account'],
  ['/academic/faculty', 'academic_faculty'],
  ['/academic/retiros', 'academic_withdrawals'],
  ['/admissions/sales', 'admissions_sales'],
  ['/ia/sofia-mejoras', 'sofia_mejoras'],
  ['/academic/camila', 'academic_camila'],
  ['/academic/grades', 'academic_grades'],
  ['/academic/groups', 'academic_groups'],
  ['/finance/flywire', 'finance_flywire_import'],
  ['/helpdesk/skills', 'helpdesk_skills'],
  ['/academic/offer', 'academic_offer'],
  ['/academic/years', 'academic_years'],
  ['/settings/sofia', 'settings_sofia'],
  ['/settings/users', 'settings_users'],
  ['/ventas/embudos', 'sales_funnels'],
  ['/academic/acta', 'academic_acta'],
  ['/contracts/new', 'contracts_new'],
  ['/inbox/metrics', 'inbox_metrics'],
  ['/planning/plan', 'planning_plan'],
  ['/desk/metrics', 'desk_metrics'],
  ['/campaigns', 'seguimiento_campaigns'],
  ['/contracts', 'contracts'],
  ['/convenios', 'convenios'],
  ['/dashboard', 'dashboard'],
  ['/finance', 'finance'],
  ['/social', 'social'],
  ['/inbox', 'inbox'],
  ['/chat', 'chat'],
  ['/desk', 'desk'],
  ['/kpis', 'kpis'],
  ['/crm', 'crm'],
  ['/hr', 'hr'],
]

export function pageKeyForPath(pathname: string): string | null {
  for (const [prefix, key] of ROUTE_TO_PAGE_KEY) {
    if (pathname === prefix || pathname.startsWith(prefix + '/')) return key
  }
  return null
}
